language: ruby
rvm:
- 2.5
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- mkdir tmp
- mkdir tmp/pids
script:
- bundle exec rspec
- bundle exec rubocop
deploy:
  provider: heroku
  app: acebook-irrelevant-pests
  on:
    repo: ffgi-es/acebook_irrelevant_pests
  run:
    - bundle exec rails db:create
    - bundle exec rails db:migrate
  api_key:
    secure: z/2iHbepZLAivW6UO3eZgnPPoCTGT3/c2yLBEi9n/qa6wZ7oV8WeHeErMb3SbGvGvluLar+OxLcaXT3nKdOwo+lldkdS+WLBoHF7Lz6z+5wZdbg2FxAJ/j1zTO1SFvlGvTKTSOIayUMS8SgUVsTmS0t33XWx035tIQXM4iRybNl7UTcOtFWW6tXSmssaB8XY+E5A07EZAzoxklP5Lpft9rrSJYV0xzPuYNqRqV/WaSFbPqJln2FGoT1mQGxqf+dUtO7NXv+YQws7s2T3ieEy5XoFLPyetVDYj3hWIraMOxXgu/aPSmTNLTlx7KHv9MI0KmnS+uDJULV3Vy/mcowt/HVVUQm2RhcHREfzKvg2xx0Zyxlbh6//WEjm+2+o9SMmDi3Ac07WtID8E0UtsvlaK7waXxjgCPow9MOSzqC9oQdG2oWShoq/Jfwm9uLRQu3enc8/UnC6m8lyORuyKO93wkATvS90Omdu3fHDKuR8DBdb/huyhgUZYD1I2ERQWNCbwkTQddu1pEzEqf5uQNFXnIxy173wnw4HZYzu6j5T9msr4eM9Fvt4h8Yh4XCVW96oHbdsVcpLhW+XMQrNIv8CfwKL/FNG+68OKfKZK8VRWDRce1YKDEfaJ+gZorSxKGBIspFN5NwGvDedl40oizVPO0So+170v6nF8nhSu1kaqvw=
